delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Bakery Camp"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Images\Bakery Camp"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Images\Colorado College"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Images\Kyle Graduation Best"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Images\Lake Chelan"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Images\Spring 2010"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Images\Winter 2010"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Colorado College"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Images"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Kyle Graduation"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Kyle Graduation Best"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Lake Chelan"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Spring 2010"
delnode "C:\Users\mikek\source\repos\romascokelly.com\images\Winter 2010"
